// Angular/src/app/components/checkbox/checkbox.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'app-checkbox',
  templateUrl: './checkbox.component.html',
  styleUrls: ['./checkbox.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CheckboxComponent),
      multi: true
    }
  ]
})
export class CheckboxComponent implements ControlValueAccessor {
  handleCheck() {
    this.value = !this.value;
    this.onChange(this.value);
  }

  writeValue(value: any): void {
    this.value = !!value;
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }
  
  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  @Input() name?: string;
  @Input() label?: string;
  @Input() supportingText?: string;

  value = false;
  onChange: any = () => {};
  onTouched: any = () => {};
}

<div class="container">
    <div class="input" [class.input-checked]="value">
        <button (click)="handleCheck()">
            <div class="checkmark-state click-ripple-effect-light">
                <img src="../../../assets/check_icon_small.svg" alt="marcado"/>
            </div>
        </button>
        <label>{{ label }}</label>
    </div>
    <span *ngIf="supportingText">{{ supportingText }}</span>
</div>

// React/src/components/checkbox/Checkbox.jsx
import { React } from "react";
import checkIcon from "./assets/check_icon_small.svg";
import "./Checkbox.css";


export default function Checkbox({ name, label, supportingText, value, onChange }) {
    return (
        <div className="checkbox-container">
            <div className={`checkbox-input${(value) ? " checkbox-input-checked" : ""}`}>
                <button className="checkbox-checkmark" onClick={() => onChange(name, !value)}>
                    <div className="checkbox-checkmark-state click-ripple-effect-light">
                        <img src={checkIcon} alt="marcado"/>
                    </div>
                </button>
                <label>{label}</label>
            </div>
            {supportingText && (
                <span className="checkbox-supporting-text">{supportingText}</span>
            )}
        </div>
    )
}
