// React/src/components/context_menu/ContextMenu.jsx
import { React, useEffect, useRef } from "react";
import editIcon from "./assets/edit_icon.svg";
import eraseIcon from "./assets/delete_icon.svg"
import finalizeIcon from "./assets/check_icon.svg";
import "./ContextMenu.css";


export default function ContextMenu({
    position,
    loanVariant,
    onMenuClick,
    onMenuClose
}) {
    let contextMenuRef = useRef(null);

    useEffect(() => {
        const checkClickOutsideMenu = (e) => {
            if(contextMenuRef.current && !contextMenuRef.current.contains(e.target)) {
                onMenuClose && onMenuClose();
            }
        };

        document.addEventListener("click", checkClickOutsideMenu);

        return () => {
            document.removeEventListener("click", checkClickOutsideMenu);
        }
    }, []);

    return (
        <div
            className="context-menu-container"
            style={{
                top: position && position.y,
                left: position && position.x
            }}
            tabIndex={0}
            ref={contextMenuRef}
        >
            <div className="context-menu-option">
                <div className="context-menu-button-container">
                    <button
                        onClick={() => {
                            onMenuClick && onMenuClick(0);
                        }}
                        className="click-ripple-effect"
                    >
                        <img src={editIcon} alt="editar"/>
                    </button>
                </div>
                <label>Editar</label>
            </div>
            <div className="context-menu-option">
                <div className="context-menu-button-container">
                    <button
                        onClick={() => {
                            onMenuClick && onMenuClick(1);
                        }}
                        className="click-ripple-effect"
                    >
                        <img src={(loanVariant) ? finalizeIcon : eraseIcon} alt={(loanVariant) ? "editar" : "apagar"}/>
                    </button>
                </div>
                <label>{(loanVariant) ? "Finalizar" : "Apagar"}</label>
            </div>
        </div>
    )
}

// Angular/src/app/components/context-menu/context-menu.component.ts
import { Component, Input, Output, EventEmitter, ElementRef, HostListener } from '@angular/core';

export interface ContextMenuPosition {
  x: number,
  y: number
}

@Component({
  selector: 'app-context-menu',
  templateUrl: './context-menu.component.html',
  styleUrls: ['./context-menu.component.css']
})
export class ContextMenuComponent {
  constructor(contextMenuContainer: ElementRef) {
    this.contextMenuContainer = contextMenuContainer;
  }

  @HostListener("document:click", ["$event"])
  handleClick(event: MouseEvent) {
    if(!this.contextMenuContainer.nativeElement?.contains(event.target)) {
      this.menuClose.emit();   
    }
  }

  @Input() loanVariant = false;
  @Input() position: ContextMenuPosition = { x: 0, y: 0 };

  @Output() menuClose = new EventEmitter<number>();

  private contextMenuContainer: ElementRef;
}

<div
    class="container"
    tab-index="0"
    [ngStyle]="{ 'top.px': position.y, 'left.px': position.x }"
    #contextMenuContainer
>
    <div class="option">
        <div class="button-container">
            <button class="click-ripple-effect" (click)="menuClose.emit(0)">
                <img src="../../../assets/edit_icon.svg" alt="editar"/>
            </button>
        </div>
        <label>Editar</label>
    </div>
    <div class="option">
        <div class="button-container">
            <button class="click-ripple-effect" (click)="menuClose.emit(1)">
                <img [src]="(loanVariant) ? '../../../assets/check_icon.svg' : '../../../assets/delete_icon.svg'" alt="editar"/>
            </button>
        </div>
        <label>{{ (loanVariant) ? "Finalizar" : "Apagar" }}</label>
    </div>
</div>
