// React/src/dialogs/state_dialog/StateDialog.jsx
import { React } from "react";
import Spinner from "../../components/spinner/Spinner";
import successIcon from "./assets/success_icon.svg";
import deleteIcon from "./assets/delete_icon.svg";
import errorIcon from "./assets/error_icon.svg";
import "./StateDialog.css";


export default function StateDialog({
    variant,
    heading,
    message,
    detailsSummary,
    detailsContent,
    buttonLabels = ["Ok"], 
    onClose
}) {
    let iconPath = successIcon;
    let altMessage = "";
    switch(variant) {
        case "success": iconPath = successIcon; altMessage = "sucesso"; break;
        case "delete":  iconPath = deleteIcon; altMessage = "apagar"; break;
        case "error": iconPath = errorIcon; altMessage = "erro"; break;
        default: iconPath = successIcon; altMessage = "";
    }

    return (
        <div className="state-dialog-container">
            {(variant !== "load") && <img src={iconPath} alt={altMessage}/>}
            <h3>{heading}</h3>
            {message.split('\n').map((paragraph, index) => (
                <p key={index}>{paragraph}</p>
            ))}
            {detailsSummary && (
                <details className="state-dialog-details">
                    <summary>{detailsSummary}</summary>
                    <div className="state-dialog-details-content">
                        {detailsContent}
                    </div>
                </details>
            )}
            {(variant === "load") ? (
                <Spinner/>
            ) : (
                <div className="state-dialog-buttons">
                    {buttonLabels.map((label, index) => (
                         <button
                            key={index}
                            onClick={() => onClose(index)}
                            className="click-ripple-effect-light"
                        >
                            {label}
                        </button>
                    ))}
                </div>
            )}
        </div>
    );
}

// Angular/src/app/dialogs/state-dialog/state-dialog.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-state-dialog',
  templateUrl: './state-dialog.component.html',
  styleUrls: ['./state-dialog.component.css']
})
export class StateDialogComponent {
  
  get iconPath() {
    switch(this.variant) {
      case "success": return "assets/success_icon.svg";
      case "delete": return "assets/delete_icon_dialog.svg";
      case "error": return "assets/error_icon.svg";
    }
    return "";  
  }
  
  get altMessage() {
    switch(this.variant) {
      case "success": return "sucesso";
      case "delete": return "apagar";
      case "error": return "erro";
    }
    return "";  
  }

  @Input() variant: "success" | "delete" | "error" | "load" = "success";
  @Input() heading = "";
  @Input() message = "";
  @Input() detailsSummary = "";
  @Input() detailsContent = "";
  @Input() buttonLabels: string[] = ["Ok"];
}

<div class="container">
    <img *ngIf="variant !== 'load'" [src]="iconPath" [alt]="altMessage"/>
    <h3>{{heading}}</h3>
    <p *ngFor="let line of message.split('\n')">{{line}}</p>
    <details *ngIf="detailsSummary">
        <summary>{{detailsSummary}}</summary>
        <div class="details-content">
            {{detailsContent}}
        </div>
    </details>
    <app-spinner *ngIf="variant === 'load'; else dialogButtons"/>
    <ng-template #dialogButtons>
        <div class="dialog-buttons">
            <button *ngFor="let label of buttonLabels; index as index"
                class="click-ripple-effect-light"
            >
                {{label}}
            </button>
        </div>
    </ng-template>
</div>
