// Angular/src/app/components/menu/menu.component.ts
import { Component, Input } from '@angular/core';


@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent {
  @Input() expanded = false;
}

<nav [className]="(expanded) ? 'side-menu-expanded' : 'side-menu-hidden'">
    <ul>
        <li><a>Acervo</a></li>
        <li><a>Empréstimos</a></li>
    </ul>
</nav>

// React/src/components/menu/Menu.jsx
import { React } from "react";
import "./Menu.css";

const PAGE_NAMES = ["Acervo", "Empréstimos"]

export default function Menu({ activePage, onPageChange }) {
    return (
        <nav className="side-menu-container">
            <ul>
                {
                    PAGE_NAMES.map(
                        (pageName, index) => <li
                        key={index}
                        className={"side-menu-item" + ((activePage === pageName) ? " side-menu-item-selected" : "")}
                        onClick={() => onPageChange(pageName)}
                        >
                            {pageName}
                        </li>
                    )
                }
            </ul>
        </nav>
    )
}
