// Angular/src/app/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  toggleMenu() {
    this.menuExpanded = !this.menuExpanded;
  }
  
  menuExpanded = false;
}

<header>
    <button class="click-ripple-effect" (click)="toggleMenu()">
        <img src="../../../assets/menu_icon.svg" alt="menu"/>
    </button>
    <h1>SimpleLibrary</h1>
</header>
<app-menu [expanded]="menuExpanded"/>

// React/src/components/header/Header.jsx
import { React, useState } from "react";
import Menu from "../menu/Menu";
import menuIcon from "./assets/menu_icon.svg";
import "./Header.css";

export default function Header() {
    const [menuExpanded, setMenuExpanded] = useState(false);

    return (
        <>
            <header className="header-container">
                <button
                    className="header-menu-button click-ripple-effect"
                    onClick={() => setMenuExpanded(!menuExpanded)}
                >
                    <img src={menuIcon} alt="menu"/>
                </button>
                <h1>SimpleLibrary</h1>
            </header>
            <Menu visible={menuExpanded} onPageChange={() => setMenuExpanded(false)}/>
        </>
    )
}
