// Svelte/src/App.svelte
<script>
  import { Router, Route } from "svelte-routing";
  import Header from "./components/Header.svelte";
  import Collection from "./pages/Collection.svelte";
  import Loans from "./pages/Loans.svelte";
  import Redirect from "./utils/Redirect.svelte";
</script>

<Router>
  <Header/>
  <Route path="/collection" component={Collection}/>
  <Route path="/loans" component={Loans}/>
  <Route>
    <Redirect to="/collection"/>
  </Route>
</Router>

// React/src/App.jsx
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import Header from "./components/header/Header";
import Collection from "./pages/Collection";
import Loans from "./pages/Loans";

function App() {

    return (
        <>
            <BrowserRouter>
                <Header/>
                <Routes>
                    <Route path="/" element={<Navigate to="/collection" push/>}/>
                    <Route path="/collection" element={<Collection/>}/>
                    <Route path="/loans" element={<Loans/>}/>
                </Routes>
            </BrowserRouter>
        </>
    )
}

export default App;
