// Angular/src/app/pages/collection/collection.component.ts
import { Component, OnInit } from '@angular/core';
import { BookService } from 'src/services/book.service';
import { ContextMenuPosition } from 'src/app/components/context-menu/context-menu.component';

interface BookDeleteState {
  variant: "delete" | "error" | "load",
  heading: string,
  message: string,
  buttonLabels?: string[],
  summary?: string,
  details?: string
}


@Component({
  selector: 'app-collection',
  templateUrl: './collection.component.html',
  styleUrls: ['./collection.component.css']
})
export class CollectionComponent implements OnInit {
  constructor(private _bookService: BookService) {

  }

  ngOnInit(): void {
    this._bookService.fetchBooks();
  }

  handleRowClick(event: MouseEvent, index: number) {
    const target = event.target as HTMLElement;
    const { top, left, width, height } = target.getBoundingClientRect();
    this.contextMenuPosition = { x: left, y: top + height };
    this.showContextMenu = true;
    this.clickTargetIndex = index;
    event.stopPropagation();
  }

  handleContextMenuClose(action?: number) {
    this.showContextMenu = false;
    if(action === 0) {

    }else if(action === 1) {
      this.deleteDialogState = {
        variant: "delete",
        heading: "Apagar Livro?",
        message: `Deseja remover o livro "${this.books[this.clickTargetIndex || 0].title}" do acervo?\nUma vez excluído, as informações desse livro não poderão ser recuperadas!`,
        buttonLabels: ["Sim", "Não"]
      };
    }
  }

  handleDeleteDialogClose(action: number) {
    if(this.deleteDialogState?.variant === "delete" && action === 0
      && this.clickTargetIndex !== null) {
        this._handleBookDelete()
    }else {
      this.deleteDialogState = null;
    }
  }

  async _handleBookDelete() {
    if(this.clickTargetIndex !== null) {
      this.deleteDialogState = {
        variant: "load",
        heading: "Salvando",
        message: "As alterações estão sendo processadas pelo sistema"
      }
      let result = await this._bookService.deleteBook(this.clickTargetIndex);
      if(result) {
        this.deleteDialogState = {
          variant: "error",
          heading: "Erro",
          message: "Ocorreu um erro ao salvar as alterações no sistema.",
          summary: "Detalhes do erro",
          details: result
        };
        return;
      }
    }
    this.deleteDialogState = null;
  }

  get booksLoading() {
    return this._bookService.status === "loading" || !this._bookService.status;
  }

  get errorLoading() {
    return this._bookService.status === "error";
  }

  get statusMessage() {
    switch(this._bookService.status) {
      case "loading": return "Carregando dados do acervo...";
      case "error": return "Ocorreu um erro ao recuperar os dados do acervo. Por favor, tente novamente.";
      default: return "Nenhum livro foi encontrado";
    }
  }

  get books() {
    return this._bookService.selectedBooks;
  }

  showContextMenu = false;
  contextMenuPosition: ContextMenuPosition = { x: 0, y: 0 };
  clickTargetIndex: number | null = null;
  deleteDialogState: BookDeleteState | null = null;
  showBookDialog = false;
}

<div class="page-container">
    <div class="header">
        <h2>Acervo</h2>
        <app-button (click)="showBookDialog = true">
            <div class="add-button">
                <img src="assets/add_icon.svg" alt="adicionar"/>
                <span>Novo livro</span>
            </div>
        </app-button>
    </div>
    <app-collection-inputs/>
    <app-table-card>
        <thead>
            <tr>
                <th>ISBN</th>
                <th>Título</th>
                <th>Autor(es)</th>
                <th>Categorias</th>
                <th>Editora</th>
                <th>Edição</th>
                <th>Formato</th>
                <th>Data</th>
                <th>Páginas</th>
                <th>Cópias</th>
                <th>Descrição</th>
                <th>Localização</th>
            </tr>
        </thead>
        <app-table-status
            *ngIf="booksLoading || errorLoading || books.length === 0; else booksData"
            [loading]="booksLoading"
            [error]="errorLoading"
            [message]="statusMessage"
        />
        <ng-template #booksData>
            <tbody>
                <tr
                    *ngFor="let book of books; index as index"
                    (click)="handleRowClick($event, index)"
                >
                    <td>{{book.isbn}}</td>
                    <td minWidth="15rem" [wrap]="true">{{book.title}}</td>
                    <td [wrap]="true">{{book.author}}</td>
                    <td minWidth="12rem" [wrap]="true">{{book.categories}}</td>
                    <td>{{book.publisher}}</td>
                    <td>{{book.edition}}</td>
                    <td>{{book.format}}</td>
                    <td>{{book.date}}</td>
                    <td>{{book.pages}}</td>
                    <td>{{book.copies}}</td>
                    <td minWidth="20rem" [wrap]="true">{{book.description}}</td>
                    <td>{{book.location}}</td>
                </tr>
            </tbody>
        </ng-template>
    </app-table-card>
    <app-context-menu
        *ngIf="showContextMenu"
        [position]="contextMenuPosition"
        (menuClose)="handleContextMenuClose($event)"
    />
    <app-dialog *ngIf="deleteDialogState">
        <app-state-dialog
            [variant]="deleteDialogState.variant"
            [heading]="deleteDialogState.heading"
            [message]="deleteDialogState.message"
            [detailsSummary]="deleteDialogState.summary"
            [detailsContent]="deleteDialogState.details"
            [buttonLabels]="deleteDialogState.buttonLabels"
            (dialogClose)="handleDeleteDialogClose($event)"
        />
    </app-dialog>
    <app-book-dialog *ngIf="showBookDialog" (dialogClose)="showBookDialog = false"/>
</div>

// React/src/pages/Collection.jsx
import { React, useState, useEffect } from "react";
import { useBooks } from "../hooks/useBooks";
import Button from "../components/button/Button";
import { TableCard, TableHeader, TableRow, TableCell, TableData } from "../components/table_card/TableCard";
import TableStatus from "../components/table_status/TableStatus";
import CollectionInputs from "../components/collection_inputs/CollectionInputs";
import ContextMenu from "../components/context_menu/ContextMenu";
import BookDialog from "../dialogs/BookDialog";
import DialogBox from "../components/dialog_box/DialogBox";
import StateDialog from "../dialogs/StateDialog";
import addIcon from "./assets/add_icon.svg";
import "./Collection.css";


export default function Collection() {
    const [showContextMenu, setShowContextMenu] = useState(false);
    const [contextMenuPosition, setContextMenuPosition] = useState({ x: 0, y: 0, targetIndex: 0 });
    const [targetBookIndex, setTargetBookIndex] = useState(null);
    const [showBookDialog, setShowBookDialog] = useState(false);
    const [showDeleteDialog, setShowDeleteDialog] = useState(false);
    const [deleteStatus, setDeleteStatus] = useState({ deleting: false, error: false });
    const { books, loadStatus, queryBooks, createBook, updateBook, deleteBook } = useBooks();

    useEffect(() => {
        document.title = "SimpleLibrary - Acervo"
    }, []);

    function handleRowClick(event, targetIndex) {
        const { top, left, width, height } = event.target.getBoundingClientRect();
        setContextMenuPosition({ x: left, y: top + height, targetIndex });
        setShowContextMenu(true);
        event.stopPropagation();
    }

    function handleContextMenuClick(action) {
        setTargetBookIndex(contextMenuPosition.targetIndex);
        setShowContextMenu(false);
        if(action === 0) {
            setShowBookDialog(true);
        }else if(action === 1) {
            setShowDeleteDialog(true);
        }
    }

    function handleBookDialogSubmit(bookData) {
        if(targetBookIndex !== null) {
            setTargetBookIndex(null);
            return updateBook(targetBookIndex, bookData);
        }else {
            return createBook(bookData);
        }
    }

    async function handleDeleteDialog(option) {
        if(option === 0  && targetBookIndex !== null) {
            setDeleteStatus({ deleting: true, error: false });
            setTargetBookIndex(null);
            let deleteStatus = await deleteBook(targetBookIndex);
            if(deleteStatus.error) {
                setDeleteStatus({ deleting: false, error: true, errorMessage: deleteStatus.errorMessage });
                return;
            }else {
                setDeleteStatus({ deleting: false, error: false });
            }
        }
        setShowDeleteDialog(false);
    }

    return (
        <div className={`collection-page${(showContextMenu) ? " collection-page-menu" : ""}`}>
            <div className="collection-header">
                <h2>Acervo</h2>
                <Button
                    variant="primary"
                    onClick={() => setShowBookDialog(true)}
                    disabled={loadStatus.loading || loadStatus.error}
                >
                    <div className="collection-add-button">
                        <img src={addIcon} alt="adicionar"/>
                        <span>Novo livro</span>
                    </div>
                </Button>
            </div>
            <CollectionInputs onSubmit={queryBooks} disabled={loadStatus.loading || loadStatus.error}/>
            <TableCard menuActive={showContextMenu}>
                <TableHeader>
                    <TableRow>
                        <TableCell>ISBN</TableCell>
                        <TableCell>Título</TableCell>
                        <TableCell>Autor(es)</TableCell>
                        <TableCell>Categorias</TableCell>
                        <TableCell>Editora</TableCell>
                        <TableCell>Edição</TableCell>
                        <TableCell>Formato</TableCell>
                        <TableCell>Data</TableCell>
                        <TableCell>Páginas</TableCell>
                        <TableCell>Cópias</TableCell>
                        <TableCell>Descrição</TableCell>
                        <TableCell>Localização</TableCell>
                    </TableRow>
                </TableHeader>
                {(loadStatus.loading || loadStatus.error || books.length === 0) ? (
                    <TableStatus
                        error={loadStatus.error}
                        loading={loadStatus.loading}
                        message={(loadStatus.loading) ? "Carregando dados do acervo..." :
                        ((loadStatus.error) ? "Ocorreu um erro ao recuperar os dados do acervo. Por favor, tente novamente." :
                        "Nenhum livro foi encontrado")}
                    />
                ) : (
                    <TableData>
                        {books.map((book, index) => (
                            <TableRow
                                key={book.id}
                                onClick={(e) => handleRowClick(e, index)}
                            >
                                <TableCell>
                                    {book.isbn}
                                </TableCell>
                                <TableCell minWidth="15rem" wrap>
                                    {book.title}
                                </TableCell>
                                <TableCell wrap>
                                    {book.author}
                                </TableCell>
                                <TableCell minWidth="12rem" wrap>
                                    {book.categories}
                                </TableCell>
                                <TableCell>
                                    {book.publisher}
                                </TableCell>
                                <TableCell>
                                    {book.edition}</TableCell>
                                <TableCell>
                                    {book.format}
                                </TableCell>
                                <TableCell>
                                    {book.date}
                                </TableCell>
                                <TableCell>
                                    {book.pages}
                                </TableCell>
                                <TableCell>
                                    {book.copies}
                                </TableCell>
                                <TableCell minWidth="20rem" wrap>
                                    {book.description}
                                </TableCell>
                                <TableCell>
                                    {book.location}
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableData>
                )}
            </TableCard>
            {showContextMenu && (
                <ContextMenu
                    position={contextMenuPosition}
                    onMenuClose={() => setShowContextMenu(false)}
                    onMenuClick={handleContextMenuClick}
                />
            )}
            {showBookDialog && (
                <BookDialog
                    updateTarget={(targetBookIndex !== null) && books[targetBookIndex]}
                    onClose={() => setShowBookDialog(false)}
                    onSubmit={handleBookDialogSubmit}
                />
            )}
            {showDeleteDialog && (
                <DialogBox>
                    {(!deleteStatus.deleting && !deleteStatus.error) ? (
                        <StateDialog
                            variant="delete"
                            heading="Apagar Livro?"
                            message={`Deseja remover o livro "${books[targetBookIndex].title}" do acervo?\nUma vez excluído, as informações desse livro não poderão ser recuperadas!`}
                            buttonLabels={["Sim", "Não"]}
                            onClose={handleDeleteDialog}
                        />
                    ) : (
                        <StateDialog
                            variant={(deleteStatus.error) ? "error" : "load"}
                            heading={(deleteStatus.error) ? "Erro" : "Salvando"}
                            message={(deleteStatus.error) ? "Ocorreu um erro ao salvar as alterações no sistema." : "As alterações estão sendo processadas pelo sistema"}
                            detailsSummary={(deleteStatus.errorMessage && deleteStatus.errorMessage !== "") && "Detalhes do erro"}
                            detailsContent={deleteStatus.errorMessage}
                            onClose={() => {
                                setShowDeleteDialog(false);
                                setDeleteStatus({ deleting: false, error: false });
                            }}
                        />  
                    )}
                </DialogBox>
            )}
        </div>
    )
}
