// React/src/components/progress_bar/ProgressBar.jsx
import { React } from "react";
import "./ProgressBar.css"

export default function ProgressBar({ width = "25rem", value }) {
    let isIndefinite = (typeof value !== "number") || value < 0 || value > 100;

    return (
        <div
            className={`progress-bar ${(isIndefinite) ? "progress-bar-indefinite" : ""}`}
            style={{
                '--filled-width': `${Math.floor(value * 100)}%`,
                "width": width
            }}
        >
        </div>
    )
}

// Angular/src/app/components/progress-bar/progress-bar.component.ts
import { Component, Input, HostBinding } from '@angular/core';

@Component({
  selector: 'app-progress-bar',
  template: `
    <div
      [ngStyle]="{ '--filled-width': value + '%'}"
      [class.indefinite]="indefinite"
    >
   
    </div>
  `,
  styleUrls: ['./progress-bar.component.css']
})
export class ProgressBarComponent {

  @Input()
  set value(value: number | undefined) {
    this._value = value && Math.floor(value * 100);
  }
  get value(): number | undefined {
    return this._value;
  }
  private _value?: number;

  get indefinite(): boolean {
    return !this._value || this._value < 0 || this._value > 100;
  }
}
