// Angular/src/app/components/search-box/search-box.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-search-box',
  templateUrl: './search-box.component.html',
  styleUrls: ['./search-box.component.css']
})
export class SearchBoxComponent {
  handleInput(event: Event) {
    this.searchQueryChange.emit((event.target as HTMLInputElement).value);
  }

  @Input() searchQuery = '';
  @Output() searchQueryChange = new EventEmitter<string>();
}

<input
    name="search-box"
    type="text"
    placeholder="Pesquise por título, descrição, autor, etc."
    [value]="searchQuery"
    (input)="handleInput($event)"
/>
<img src="../../../assets/search_icon.svg" alt="search"/>

// React/src/components/search-box/SearchBox.jsx
import { React } from "react";
import searchIcon from "./assets/search_icon.svg";
import "./SearchBox.css";


export default function SearchBox({ searchQuery, onQueryChange }) {
    return (
        <div className="search-box">
            <input
                name="search-box"
                type="text"
                placeholder="Pesquise por título, descrição, autor, etc."
                value={searchQuery}
                onChange={(e) => onQueryChange && onQueryChange(e.target.value)}
            />
            <img src={searchIcon} alt="search"/>
        </div>
    )
}
