// React/src/components/table_status/TableStatus.jsx
import { React } from "react";
import ProgressBar from "../progress_bar/ProgressBar";
import errorIcon from "./assets/error_icon.svg";
import "./TableStatus.css";


export default function TableStatus({ loading, error, message }) {
    return (
        <tbody>
            <tr>
                <td>
                    <div className="load-status-container">
                        {(error) && <img src={errorIcon} alt="Erro"/>}
                        {(loading) && <ProgressBar/>}
                        <p>
                            {message}
                        </p>
                    </div>
                </td>
            </tr>
        </tbody>
    )
}

// Angular/src/app/components/table-status/table-status.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-table-status',
  templateUrl: './table-status.component.html',
  styleUrls: ['./table-status.component.css']
})
export class TableStatusComponent {
  @Input() loading = false;
  @Input() error = false;
  @Input() message = "";
}

<tbody>
    <tr>
        <td>
            <div>
                <img *ngIf="error" src="assets/error_icon.svg" alt="error"/>
                <app-progress-bar *ngIf="loading"/>
                <p>
                    {{ message }}
                </p>
            </div>
        </td>
    </tr>
</tbody>
