// Angular/src/app/components/collection-inputs/collection-inputs.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-collection-inputs',
  templateUrl: './collection-inputs.component.html',
  styleUrls: ['./collection-inputs.component.css']
})
export class CollectionInputsComponent {

  @Input() disabled = false;
}

<div class="input-card">
    <div class="titles">
        <h3>Pesquisa no acervo:</h3>
        <h3>Refine sua busca:</h3>
    </div>
    <div class="inputs">
        <div class="search-box-container">
            <app-search-box/>
        </div>
        <div class="select-container">
            <app-select
                name="author"
                label="Autor"
                placeholder="Todos"
            />
        </div>
        <div class="select-container">
            <app-select
                name="categories"
                label="Categoria"
                placeholder="Todas"
            />
        </div>
        <div class="select-container">
            <app-select
                name="publisher"
                label="Editora"
                placeholder="Todas"
            />
        </div>
        <div class="select-container">
            <app-select
                name="format"
                label="Formato"
                placeholder="Todos"
            />
        </div>
        <div class="buttons-container">
            <app-button variant="secondary" [disabled]="disabled">
                Redefinir
            </app-button>
            <app-button variant="secondary" [disabled]="disabled">
                Pesquisar
            </app-button>
        </div>
    </div>
</div>

// React/src/components/collection_inputs/CollectionInputs.jsx
import { React } from "react";
import { useBookFilters } from "../../hooks/useBookFilters";
import SearchBox from "../search_box/SearchBox";
import Select from "../select/Select";
import Button from "../button/Button";
import "./CollectionInputs.css";


export default function CollectionInputs() {
    const { authors, categories, publishers, formats } = useBookFilters();

    return (
        <div className="collection-input-card">
            <div className="collection-input-titles">
                <h3>Pesquisa no acervo:</h3>
                <h3>Refine sua busca:</h3>
            </div>
            <div className="collection-inputs">
                <div className="collection-search-box-container">
                    <SearchBox/>
                </div>
                <div className="cinputs-select-container">
                    <Select
                        label="Autor"
                        options={authors}
                        placeholder="Todos"
                    />
                </div>
                <div className="cinputs-select-container">
                    <Select
                        label="Categoria"
                        options={categories}
                        placeholder="Todos"
                    />
                </div>
                <div className="cinputs-select-container">
                    <Select
                        label="Editora"
                        options={publishers}
                        placeholder="Todos"
                    />
                </div>
                <div className="cinputs-select-container">
                    <Select
                        label="Formato"
                        options={formats}
                        placeholder="Todos"
                    />
                </div>
                <div className="cinputs-button-container">
                    <Button variant="secondary">Pesquisar</Button>
                </div>
            </div>
        </div>
    );
}
