// React/src/components/select/Select.jsx
import { React, useState, useEffect, useRef } from "react";
import resetIcon from "./assets/cancel_icon.svg";
import "./Select.css";


export default function Select({
    name = "",
    label,
    options = [],
    optionValues = [],
    placeholder,
    multiple,
    formVariant,
    errorMessage = "Por favor, selecione uma opção",
    onChange,
    value,
    disabled,
    required
}) {
    const [active, setActive] = useState(false);
    const [selectedIndexes, setSelectedIndexes] = useState([]);
    const [error, setError] = useState("");
    const selectElementRef = useRef(null);
    const values = (optionValues.length > 0) ? optionValues : options;

    useEffect(() => {
        const checkClickOutsideList = (e) => {
            if(selectElementRef.current && !selectElementRef.current.contains(e.target)) {
                setActive(false);
                setError((e.target.validationMessage && e.target.validationMessage !== "") ? errorMessage : "");
            }
        };

        document.addEventListener("click", checkClickOutsideList);

        return () => {
            document.removeEventListener("click", checkClickOutsideList);
        }
    }, []);

    useEffect(() => {
        const values = (optionValues.length > 0) ? optionValues : options;
        if(Array.isArray(value)) {
            setSelectedIndexes(value.map((optionValue) => values.indexOf(optionValue)));
        }else if(value && value !== "") {
            setSelectedIndexes([values.indexOf(value)]);
        }else {
            setSelectedIndexes([]);
        }
    }, [options, value])

    return (
        <div
            className={`select-container${(formVariant) ? " select-container-form" : ""}${(active) ? " select-container-active": ""}${(error) ? " select-container-error" : ""}`}
            onClick={() => setActive(true)}
            onKeyDown={(e) => e.key === "Enter" && setActive(false)} 
            ref={selectElementRef}
        >
            <div className="select-input">
                <div className="select-header">
                    <div className="select-name">
                        {label}
                    </div>
                    <input
                        type="text"
                        className="select-selected-option"
                        value={(selectedIndexes.length > 0) ? selectedIndexes.map((index) => options[index]).join("; ") : ""}
                        placeholder={(error && errorMessage !== "") ? errorMessage : placeholder}
                        required={required}
                        onInvalid={(e) => setError(errorMessage)}
                    />
                </div>
                <button
                    onClick={(e) => {
                        e.preventDefault()
                        setActive(false);
                        setSelectedIndexes([]);
                        onChange(name, (multiple) ? [] : "");
                        e.stopPropagation();
                    }}
                >
                    <img src={resetIcon} alt="redefinir"/>
                </button>
            </div>
            {active && (
                <div className="select-item-list-container">
                    <ul
                        className="select-item-list"
                    >
                        {options.map((optionLabel, index) => (
                            <li
                                key={index}
                                className={`click-ripple-effect-light ${(selectedIndexes.includes(index)) ? "select-item-selected" : ""}`}
                                onClick={(e) => {
                                    if(disabled) {
                                        setActive(false);
                                        e.stopPropagation();
                                        return;
                                    }
                                    if(multiple) {
                                        let newSelectedIndexes;
                                        if(selectedIndexes.includes(index)) {
                                            newSelectedIndexes = selectedIndexes.filter((selectedIndex) => selectedIndex !== index);
                                        }else {
                                            newSelectedIndexes = [...selectedIndexes, index];
                                        }
                                        setSelectedIndexes(newSelectedIndexes);
                                        onChange(name, newSelectedIndexes.map((selectedIndex) => values[selectedIndex]));
                                    }else {
                                        setSelectedIndexes([index]);
                                        onChange(name, values[index]);
                                        setActive(false);
                                        e.stopPropagation()
                                    }
                                }}
                            >
                                {optionLabel}
                            </li>
                        ))}
                    </ul>
                </div>
            )}
        </div>
    )
}

// Angular/src/app/components/select/select.component.ts
import { Component, Input, OnChanges, ElementRef, HostListener, SimpleChanges, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'app-select',
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => SelectComponent),
      multi: true
    }    
  ]
})
export class SelectComponent implements OnChanges, ControlValueAccessor {
  constructor(selectElement: ElementRef) {
    this.selectElementRef = selectElement;
  }

  ngOnChanges(changes: SimpleChanges) {
    if(changes["options"] || changes["optionValues"]) {
      this.optionValuesMap = (this.optionValues.length > 0) ? this.optionValues : this.options;
    }
  }

  @HostListener("document:click", ["$event"])
  handleDocumentClick(event: MouseEvent) {
    if(!this.selectElementRef.nativeElement.contains(event.target)) {
      this.active = false;
    }
  }

  writeValue(newValue: string | string[]) {
    this.value = newValue;
    if(Array.isArray(newValue)) {
      this.selectedIndexes = newValue.map((value) => this.optionValuesMap.indexOf(value));
    }else if(newValue && newValue !== "") {
      this.selectedIndexes = [this.optionValuesMap.indexOf(this.value)];
    }else {
      this.selectedIndexes = [];
    }
  }
  
  registerOnChange(fn: any) {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    
  }
  
  setDisabledState(isDisabled: boolean) {
    this.disabled = isDisabled;
  }

  handleOptionClick(event: MouseEvent, optionIndex: number) {
    if(this.disabled) {
      this.active = false;
      event.stopPropagation();
      return;
    }
    if(this.multiple) {
      if(this.selectedIndexes.includes(optionIndex)) {
        this.selectedIndexes = this.selectedIndexes.filter((selectedIndex) => selectedIndex !== optionIndex);
      }else {
        this.selectedIndexes.push(optionIndex);
      }
      this.value = this.selectedIndexes.map((selectedIndex) => this.optionValuesMap[selectedIndex]);
      this.onChange(this.value);
    }else {
      event.stopPropagation();
      this.selectedIndexes = [optionIndex];
      this.active = false;
      this.value = this.optionValuesMap[optionIndex];
      this.onChange(this.value);
    }
  }

  handleClearButtonClick(event: MouseEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.active = false;
    this.selectedIndexes = [];
    this.value = this.multiple ? [] : "";
    this.onChange(this.value);
  }

  generateInputValue() {
    if(this.selectedIndexes.length > 0) {
      return this.selectedIndexes.map(
        (optionIndex) => this.options[optionIndex]
      ).join("; ");
    }
    return "";
  }

  @Input() name = "";
  @Input() label = "";
  @Input() options: string[] = [];
  @Input() optionValues: any[] = [];
  @Input() placeholder?: string;
  @Input() multiple = false;
  @Input() formVariant = false;
  @Input() errorMessage = "Por favor, selecione uma opção";
  @Input() disabled = false;
  @Input() required = false;
  
  active = false;
  value: string | string[] = "";
  onChange: any = () => {};
  optionValuesMap = (this.optionValues.length > 0) ? this.optionValues : this.options;
  selectedIndexes: number[] = [];
  private selectElementRef: ElementRef;
}

<div
    [class]="{
        container: true,
        'container-form': formVariant,
        'container-active': active,
        'container-error': error
    }"
    tabindex="0"
    (click)="active = true"
    (keydown.enter)="active = false"
>
    <div class="input">
        <div class="header">
            <div class="name">
                {{ label }}
            </div>
            <input
                #inputModel="ngModel"
                type="text"
                class="selected-option"
                [name]="name"
                [placeholder]="inputPlaceholder"
                [required]="required"
                [ngModel]="generateInputValue()"
            />
        </div>
        <button (click)="handleClearButtonClick($event)">
            <img src="../../../assets/cancel_icon.svg" alt="redefinir"/>
        </button>
    </div>
    <div *ngIf="active" class="item-list-container">
        <ul class="item-list">
            <li
                *ngFor="let option of options; index as index"
                class="click-ripple-effect-light"
                [class.item-selected]="selectedIndexes.includes(index)"
                (click)="handleOptionClick($event, index)"
            >
                {{ option }}
            </li>
        </ul>
    </div>
</div>
