// Angular/src/app/components/text-area/text-area.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'app-text-area',
  templateUrl: './text-area.component.html',
  styleUrls: ['./text-area.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => TextAreaComponent),
      multi: true
    }
  ]
})
export class TextAreaComponent implements ControlValueAccessor {
  handleFocusIn() {
    this.active = true;
  }

  handleFocusOut() {
    this.active = false;
  }

  handleInput(newValue: string) {
    this.value = newValue;
    this.onValueChange(newValue);
  }

  writeValue(value: string) {
    this.value = value;
  }

  handleClearButtonClick(event: Event) {
    this.value = this.defaultValue;
    this.onValueChange(this.defaultValue);
  }

  registerOnChange(fn: any) {
    this.onValueChange = fn;
  }

  registerOnTouched(fn: any) {
    
  }

  @Input() name = "";
  @Input() label = "";
  @Input() supportingText = "";
  @Input() minLength?: number;
  @Input() maxLength?: number;
  @Input() required = false;
  @Input() defaultValue = "";
  @Input() errorMessage = "";


  value = '';
  onValueChange: any = () => {};
  active = false;
  error = false;
}

<div class="container" [ngClass]="{'container-active': active, 'container-error': error}">
    <label>{{ label }}</label>
    <div class="control"  [ngClass]="{'control-active': active, 'control-error': error}">
        <textarea
            [name]="name"
            [minlength]="minLength || null"
            [maxlength]="maxLength || null"
            [required]="required"
            [ngModel]="value"
            (ngModelChange)="handleInput($event)"
            (focus)="handleFocusIn()"
            (blur)="handleFocusOut()"
        >
        </textarea>
        <button (click)="handleClearButtonClick($event)">
            <img src="../../../assets/cancel_icon.svg" alt="limpar"/>
        </button>
    </div>
    <span *ngIf="errorMessage; else supportText" class="error-message">{{ errorMessage }}</span>
    <ng-template #supportText>
        <span *ngIf="supportingText" class="support-text">{{ supportingText }}</span>
    </ng-template>
</div>

// React/src/components/textarea/TextArea.jsx
import { React, useState } from "react";
import clearIcon from "./assets/cancel_icon.svg";
import "./TextArea.css";


export default function TextArea({
    label = "",
    supportingText = "",
    minLength,
    maxLength,
    required,
    defaultValue = "",
    error,
    errorMessage,
    value,
    onChange
}) {
    let [isActive, setIsActive] = useState(false);

    return (
        <div
            className={`textarea-container${(isActive) ? " textarea-container-active" : ""}${(error) ? " textarea-container-error" : ""}`}
        >
            <label>{label}</label>
            <div className={`textarea-control${(error) ? " textarea-control-error" : ""}`}>
                <textarea
                    value={value}
                    minLength={minLength}
                    maxLength={maxLength}
                    required={required}
                    onChange={(e) => onChange(e.target.value)}
                    onFocus={() => setIsActive(true)}
                    onBlur={() => setIsActive(false)}
                />
                <button
                    onClick={(e) => {
                        onChange(defaultValue);
                        e.preventDefault();
                    }}
                >
                    <img src={clearIcon} alt="limpar"/>
                </button>
            </div>
            {(!error && supportingText) && <span className="textarea-support">{supportingText}</span>}
            {(error && errorMessage) && <span className="textarea-error-message">{errorMessage}</span>}
        </div>
    )
}
