// Angular/src/app/components/spinner/spinner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-spinner',
  templateUrl: './spinner.component.html',
  styleUrls: ['./spinner.component.css']
})
export class SpinnerComponent {
  @Input() diameter = "65px";
  @Input() color = "#7e5700";
}

<svg viewBox="0 0 66 66" [attr.width]="diameter" [attr.height]="diameter">
    <circle
        fill="none"
        [attr.stroke]="color"
        stroke-width="6"
        stroke-linecap="round"
        cx="33"
        cy="33"
        r="30"
    />
</svg>

// React/src/components/spinner/Spinner.jsx
import { React } from "react";
import "./Spinner.css";


export default function Spinner({ diameter = "65px", color = "#7e5700" }) {
    return (
        <svg class="spinner" width={diameter} height={diameter} viewBox="0 0 66 66">
            <circle
                class="spinner-circle"
                fill="none"
                stroke={color}
                stroke-width="6"
                stroke-linecap="round"
                cx="33"
                cy="33"
                r="30"
            />
        </svg>
    )
}
