// React/src/components/collection_inputs/CollectionInputs.jsx
import { React, useState } from "react";
import { useBookFields } from "../../hooks/useBookFields";
import SearchBox from "../search_box/SearchBox";
import Select from "../select/Select";
import Button from "../button/Button";
import "./CollectionInputs.css";

const FIELD_LOADING_MESSAGE = "Carregando...";
const FIELD_LOADING_ERROR = "Ocorreu um erro ao carregar as opções do filtro";
const DEFAULT_FILTER_VALUES = {
    author: "",
    categories: "",
    publisher: "",
    format: ""
};

function getOptionsFromField(field) {
    if(field.loading) {
        return [FIELD_LOADING_MESSAGE];
    }
    if(field.error) {
        return [FIELD_LOADING_ERROR];
    }
    return field.fieldData;
}


export default function CollectionInputs({ onSubmit, disabled }) {
    const [searchQuery, setSearchQuery] = useState("");
    const [filters, setFilters] = useState(DEFAULT_FILTER_VALUES);
    const { authors, categories, publishers, formats } = useBookFields();

    function handleSelectChange(name, option) {
        setFilters({ ...filters, [name]: option });
    }

    return (
        <div className="collection-input-card">
            <div className="collection-input-titles">
                <h3>Pesquisa no acervo:</h3>
                <h3>Refine sua busca:</h3>
            </div>
            <div className="collection-inputs">
                <div className="cinputs-search-box-container">
                    <SearchBox
                        searchQuery={searchQuery}
                        onQueryChange={setSearchQuery}
                    />
                </div>
                <div className="cinputs-select-container">
                    <Select
                        name="author"
                        label="Autor"
                        options={getOptionsFromField(authors)}
                        placeholder="Todos"
                        value={filters.author}
                        onChange={handleSelectChange}
                        disabled={authors.loading || authors.error}
                    />
                </div>
                <div className="cinputs-select-container">
                    <Select
                        name="categories"
                        label="Categoria"
                        options={getOptionsFromField(categories)}
                        placeholder="Todas"
                        value={filters.categories}
                        onChange={handleSelectChange}
                        disabled={categories.loading || categories.error}
                        multiple
                    />
                </div>
                <div className="cinputs-select-container">
                    <Select
                        name="publisher"
                        label="Editora"
                        options={getOptionsFromField(publishers)}
                        placeholder="Todas"
                        value={filters.publisher}
                        onChange={handleSelectChange}
                        disabled={publishers.loading || publishers.error}
                    />
                </div>
                <div className="cinputs-select-container">
                    <Select
                        name="format"
                        label="Formato"
                        options={getOptionsFromField(formats)}
                        placeholder="Todos"
                        value={filters.format}
                        onChange={handleSelectChange}
                        disabled={formats.loading || formats.error}
                    />
                </div>
                <div className="cinputs-button-container">
                    <Button
                        variant="secondary"
                        onClick={(e) => {
                            setFilters(DEFAULT_FILTER_VALUES);
                            setSearchQuery("");
                            onSubmit("", DEFAULT_FILTER_VALUES);
                            e.target.blur();
                        }}
                        disabled={disabled}
                    >
                        Redefinir
                    </Button>
                    <Button
                        variant="secondary"
                        onClick={(e) => {
                            onSubmit(searchQuery, filters);
                            e.target.blur();
                        }}
                        disabled={disabled}
                    >
                        Pesquisar
                    </Button>
                </div>
            </div>
        </div>
    );
}

// Svelte/src/components/CollectionInputs.svelte
<script>
    import { createEventDispatcher } from "svelte";
    import SearchBox from "./SearchBox.svelte";
    import Select from "./form_components/Select.svelte";
    import Button from "./Button.svelte";

    export let author = [];
    export let categories = [];
    export let publisher = [];
    export let format = [];

    const dispatch = createEventDispatcher();
    const FIELD_LOADING_MESSAGE = "Carregando...";
    const FIELD_LOADING_ERROR = "Ocorreu um erro ao carregar as opções do filtro";

    function getOptionsFromField(field) {
        if(field.loading) {
            return [FIELD_LOADING_MESSAGE];
        }
        if(field.error) {
            return [FIELD_LOADING_ERROR];
        }
        return field.fieldData;
    }   

    let query = "";
    let filters = {
        author: "",
        categories: [],
        publisher: "",
        format: ""
    };
</script>

<style>
    .input-card {
        display: flex;
        flex-flow: column nowrap;
        padding: 1.5rem;
        background: linear-gradient(0deg, rgba(126, 87, 0, 0.05), rgba(126, 87, 0, 0.05)), #fffbff;
        box-shadow: 0px 2.32778px 4.65556px rgba(0, 0, 0, 0.3), 0px 4.65556px 13.9667px 4.65556px rgba(0, 0, 0, 0.15);
        border-radius: 1.75rem;
        flex: 0;
    }

    .titles {
        display: flex;
        flex-flow: row nowrap;
        justify-content: flex-start;
        padding: 0.5rem 1.5rem;
    }

    .titles h3 {
        font-size: 1.4rem;
        font-weight: 500;
        color: #1f1b16;
        line-height: 1.75rem;
    }

    .titles h3:nth-child(2) {
        margin: auto;
    }

    .inputs {
        display: flex;
        flex-flow: row wrap;
        align-items: center;
        justify-content: space-around;
        gap: 1.2rem;
        padding: 1rem;
    }

    .search-box-container {
        flex: 1 1;
        max-width: 20rem;
    }

    .select-container {
        width: 15rem;
    }

    .buttons-container {
        flex: 0;
        display: flex;
        flex-flow: row nowrap;
        gap: 1.2em;
    }
</style>

<div class="input-card">
    <div class="titles">
        <h3>Pesquisa no acervo:</h3>
        <h3>Refine sua busca:</h3>
    </div>
    <div class="inputs">
        <div class="search-box-container">
            <SearchBox bind:searchQuery={query}/>
        </div>
        <div class="select-container">
            <Select
                name="author"
                label="Autor"
                placeholder="Todos"
                options={getOptionsFromField($author)}
                bind:value={filters.author}
            />
        </div>
        <div class="select-container">
            <Select
                name="categories"
                label="Categoria"
                placeholder="Todas"
                multiple
                options={getOptionsFromField($categories)}
                bind:value={filters.categories}
            />
        </div>
        <div class="select-container">
            <Select
                name="publisher"
                label="Editora"
                placeholder="Todas"
                options={getOptionsFromField($publisher)}
                bind:value={filters.publisher}
            />
        </div>
        <div class="select-container">
            <Select
                name="format"
                label="Formato"
                placeholder="Todos"
                options={getOptionsFromField($format)}
                bind:value={filters.format}
            />
        </div>
        <div class="buttons-container">
            <Button
                variant="secondary"
                on:click={() => dispatch("submit", { query: "", filters: {} })}
            >
                Redefinir
            </Button>
            <Button
                variant="secondary"
                on:click={() => dispatch("submit", { query, filters })}
            >
                Pesquisar
            </Button>
        </div>
    </div>
</div>
