// Angular/src/app/components/date-picker/date-picker.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'app-date-picker',
  templateUrl: './date-picker.component.html',
  styleUrls: ['./date-picker.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => DatePickerComponent),
      multi: true
    }
  ]
})
export class DatePickerComponent implements ControlValueAccessor {
  handleFocusIn() {
    this.active = true;
  }

  handleFocusOut() {
    this.active = false;
  }

  handleInput(newValue: any) {
    this.value = newValue;
    this.onValueChange(this.value);
  }

  writeValue(value: any) {
    this.value = value;
  }

  registerOnChange(fn: any): void {
    this.onValueChange = fn;
  }

  registerOnTouched(fn: any): void {

  }

  @Input() name = "";
  @Input() label = "";
  @Input() supportingText = "";
  @Input() minDate?: number;
  @Input() maxDate?: number;
  @Input() required = false;
  @Input() errorMessage = "";
  @Input() formVariant = false;

  value: any = '';
  onValueChange: any = () => {};
  active = false;
  error = false;
}

<div class="container" [ngClass]="{ 'container-form': formVariant, 'container-active': active, 'container-error': error }">
    <label [class.active]="active">{{ label }}</label>
    <div class="control" [class.control-error]="error">
        <input
            type="date"
            [min]="minDate"
            [max]="maxDate"
            [required]="required"
            [ngModel]="value"
            (ngModelChange)="handleInput($event)"
            (focus)="handleFocusIn()"
            (blur)="handleFocusOut()"
        />
    </div>
    <span *ngIf="error; else supporting" class="error-message">
        {{ errorMessage }}
    </span>
    <ng-template #supporting>
        <span *ngIf="supportingText" class="support-message">{{ supportingText }}</span>
    </ng-template>
</div>

// React/src/components/date_picker/DatePicker.jsx
import { React, useState } from "react";
import "./DatePicker.css";


export default function DatePicker({
    name = "",
    label = "",
    supportingText = "",
    minDate,
    maxDate,
    required,
    errorMessage,
    formVariant,
    value,
    onChange
}) {
    const [isActive, setIsActive] = useState(false);
    const [error, setError] = useState("");

    return (
        <div
            className={`date-picker-container ${formVariant && "date-picker-container-form"}${(isActive) ? " date-picker-container-active" : ""}${(!!error) ? " date-picker-container-error" : ""}`}
        >
            <label className={(isActive || value) ? "date-picker-small-label" : ""}>{label}</label>
            <div className={`date-picker-control${(!!error) ? " date-picker-control-error" : ""}`}>
                <input
                    type="date"
                    value={value}
                    min={minDate}
                    max={maxDate}
                    required={required}
                    onChange={(e) => onChange(name, e.target.value)}
                    onFocus={() => setIsActive(true)}
                    onBlur={(e) => {
                        setError(e.target.validationMessage);
                        setIsActive(false);
                    }}
                    onInvalid={(e) => setError(e.target.validationMessage)}
                />
            </div>
            {(!!error) ? (
                <span className="date-picker-error-message">{errorMessage || error}</span>
            ) : (
                supportingText && <span className="date-picker-support">{supportingText}</span>
            )}
        </div>
    )
}
