// Angular/src/app/components/input/input.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'app-input',
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => InputComponent),
      multi: true
    }
  ]
})
export class InputComponent implements ControlValueAccessor {
  writeValue(newValue: any) {
    this.value = newValue;
  }
  
  registerOnChange(fn: any) {
    this.onValueChange = fn;
  }
  
  registerOnTouched(fn: any) {

  }

  setDisabledState(isDisabled: boolean) {
    this.disabled = isDisabled;
  }

  handleInput(newValue: any) {
    if(this.type === "number") {
      this.value = parseFloat(newValue);
    }else {
      this.value = newValue;
    }
    this.onValueChange(this.value);
  }

  handleFocusIn() {
    this.active = true;
  }

  handleFocusOut() {
    this.active = false;
  }

  handleClearButtonClick(event: MouseEvent) {
    event.preventDefault();
    this.value = "";
    this.onValueChange("");
  }

  @Input() name = "";
  @Input() label = "";
  @Input() supportingText = "";
  @Input() type = "text";
  @Input() minLength?: number;
  @Input() maxLength?: number;
  @Input() minValue?: number;
  @Input() maxValue?: number;
  @Input() step?: number;
  @Input() validationPattern?: string;
  @Input() required = false;
  @Input() autofocus = false;
  @Input() defaultValue = "";
  @Input() errorMessage = "";

  value: any = "";
  onValueChange: any = () => {};
  disabled = false;
  active = false;
  error = false;
}

<div class="container" [ngClass]="{ 'container-error': error, 'container-active': active }">
    <label [class.small-label]="active || value">{{ label }}</label>
    <div class="control" [class.control-error]="error">
        <input
            [attr.name]="name || null"
            [type]="type"
            [attr.minLength]="minLength || null"
            [attr.maxLength]="maxLength || null"
            [attr.min]="minValue || null"
            [attr.max]="maxValue || null"
            [attr.step]="step || null"
            [attr.pattern]="validationPattern || null"
            [required]="required"
            [autofocus]="autofocus"
            [ngModel]="value"
            (ngModelChange)="handleInput($event)"
            (focus)="handleFocusIn()"
            (blur)="handleFocusOut()"
        />
        <button (click)="handleClearButtonClick($event)">
            <img src="../../../assets/cancel_icon.svg" alt="limpar"/>
        </button>
    </div>
    <span *ngIf="error; else supporting" class="error-message">
        {{ errorMessage }}
    </span>
    <ng-template #supporting>
        <span *ngIf="supportingText" class="support-message">
            {{ supportingText }}
        </span>
    </ng-template>
</div>

// React/src/components/input/Input.jsx
import { React, useState } from "react";
import clearIcon from "./assets/cancel_icon.svg";
import "./Input.css";


export default function Input({
    name = "",
    label = "",
    supportingText = "",
    type = "text",
    minLength,
    maxLength,
    minValue,
    maxValue,
    step,
    validationPattern,
    required,
    defaultValue = "",
    error,
    errorMessage,
    value,
    onChange
}) {
    const [isActive, setIsActive] = useState(false);

    return (
        <div
            className={`input-container${(isActive) ? " input-container-active" : ""}${(error) ? " input-container-error" : ""}`}
        >
            <label className={(isActive || value) ? "input-small-label" : ""}>{label}</label>
            <div className={`input-control${(error) ? " input-control-error" : ""}`}>
                <input
                    name={name}
                    type={type}
                    value={value}
                    minLength={minLength}
                    maxLength={maxLength}
                    min={minValue}
                    max={maxValue}
                    step={step}
                    pattern={validationPattern}
                    required={required}
                    onChange={(e) => onChange(name, e.target.value)}
                    onFocus={() => setIsActive(true)}
                    onBlur={() => setIsActive(false)}
                />
                <button
                    onClick={(e) => {
                        onChange(name, defaultValue);
                        e.preventDefault();
                    }}
                >
                    <img src={clearIcon} alt="limpar"/>
                </button>
            </div>
            {(!error && supportingText) && <span className="input-support">{supportingText}</span>}
            {(error && errorMessage) && <span className="input-error-message">{errorMessage}</span>}
        </div>
    )
}
