// React/src/components/button/Button.jsx
import { React } from "react";
import "./Button.css";


export default function Button({ children, variant, onClick, disabled = false }) {
    variant = (/primary|secondary/.test(variant)) ? variant : "primary";

    return (
        <button
            className={`material-button material-button-${variant}`}
            onClick={onClick}
            disabled={disabled}
            aria-disabled={disabled}
        >
            {children}
        </button>
    )
}

// Angular/src/app/components/button/button.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-button',
  template: `
    <button [class]="variant" [disabled]="disabled" [attr.aria-disabled]="disabled">
      <ng-content/>
    </button>
  `,
  styleUrls: ['./button.component.css']
})
export class ButtonComponent {

  @Input() variant: "primary" | "secondary" = "primary";
  @Input() disabled = false;
}
